# Kitty config: Ubuntu theme

font_family IosevkaTerm Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 15.0

window_padding_width 10

scrollback_lines 10000

cursor_shape block
cursor_blink_interval 0.5

mouse_hide_wait 3.0

# Ubuntu colors
background #300a24
foreground #ffffff

# Normal colors
color0 #2e3436
color1 #cc0000
color2 #4e9a06
color3 #c4a000
color4 #3465a4
color5 #75507b
color6 #06989a
color7 #d3d7cf

# Bright colors
color8  #555753
color9  #ef2929
color10 #8ae234
color11 #fce94f
color12 #729fcf
color13 #ad7fa8
color14 #34e2e2
color15 #eeeeec
